---
- name: Add python modules
  raw: >
      test -e /usr/bin/python ||
      export http_proxy={{hostvars['localhost'].lagoon_configuration_params.proxy.http_proxy}} &&
      export https_proxy={{hostvars['localhost'].lagoon_configuration_params.proxy.https_proxy}} &&
      export no_proxy={{hostvars['localhost'].lagoon_configuration_params.proxy.no_proxy}} &&
      apt -y update && apt install -y python-minimal
  when: hostvars['localhost'].lagoon_configuration_params.proxy is mapping 
  changed_when: false
  become: true

- name: Add python modules
  raw: >
      test -e /usr/bin/python ||
      apt -y update && apt install -y python-minimal
  when: hostvars['localhost'].lagoon_configuration_params.proxy is not mapping 
  changed_when: false
  become: true

- setup:

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: true
  become: true
  environment: "{{hostvars['localhost'].lagoon_configuration_params.proxy}}"

- name: Install NFS dependencies for backup
  become: true
  apt:
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
  - apt-transport-https
  - ca-certificates
  - nfs-common
  - python
  - ntp
  environment: "{{hostvars['localhost'].lagoon_configuration_params.proxy}}"

- name: Update all packages to the latest version
  apt:
    upgrade: dist
  become: true
  register: upgradeMachine
  environment: "{{hostvars['localhost'].lagoon_configuration_params.proxy}}"

- name: reboot server
  become: true
  shell: sleep 2 && /sbin/shutdown -r now "System reboot"
  async: 1
  poll: 0
  when: upgradeMachine.changed

- pause: seconds=10
  when: upgradeMachine.changed

- name: Wait for restart
  become: false
  wait_for_connection:
    delay: 5
    timeout: 180
  when: upgradeMachine.changed
