---
- name: Execute common pre-install tasks
  include_tasks: common/pre/install.yml
- name: Execute Debian/Ubuntu install tasks
  include_tasks: ubuntu/install.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Execute common post-install tasks
  include_tasks: common/post/install.yml
