---
- name: Check if fuser exists
  stat: 
    path: /bin/fuser
  register: ek_fuser_result
  
- name: Wait for APT to stop
  when: ek_fuser_result.stat.exists == True
  become: true
  raw: fuser /var/lib/apt/lists/lock
  register: ek_install_lock_result
  until: ek_install_lock_result.rc == 1
  retries: 120
  delay: 1
  failed_when: ek_install_lock_result.rc == 0
  changed_when: false
  ignore_errors: true

- name: APT still running
  fail:
    msg: "The system cannot be further installed because another APT command is still running."
  when: ek_install_lock_result is defined and ek_install_lock_result.rc == 0

- name: Ensure that preliminary dependencies are present
  become: true
  environment: "{{ proxy_env_vars }}"
  apt:
    state: latest
    update_cache: true
    name:
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: Get Docker official GPG key
  become: true
  environment: "{{ proxy_env_vars }}"
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
    
- name: Add Docker stable repository
  become: true
  environment: "{{ proxy_env_vars }}"
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Ensure that required dependencies are installed
  become: true
  environment: "{{ proxy_env_vars }}"
  apt:
    state: latest
    update_cache: true
    name:
    - nfs-common
    - ntp
    - python3
    - python3-pip
    - docker-ce
    - docker-compose
